name: "Terraform Deployment"
on:
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
jobs:
  terraform:
    name:   ${{matrix.runner}} - dev
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: test
             runner: ubuntu-latest
    env:
         AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 905975536748.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: coforma-acme-challenge-app
        run: |
          # Build a docker container and push it to ECR
          export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
          docker build --quiet -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          export APP_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::${APP_IMAGE}"
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        working-directory: infracode/app
        run: |
           rm -rf .terraform
           terraform init -backend-config=dev/backend.tfvars -upgrade=true -no-color -input=false
      - name: Terraform Plan
        id: plan
        working-directory: infracode/app
        run: |
          terraform plan -input=false -var-file=dev/terraform.tfvars -var "app_image=$APP_IMAGE" -no-color
        env:
          APP_IMAGE: ${{steps.build-image.outputs.image}}
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        id: apply
        working-directory: infracode/app
        run:  |
          terraform apply -auto-approve -input=false -var-file=dev/terraform.tfvars -var "app_image=$APP_IMAGE"
        env:
          APP_IMAGE: ${{steps.build-image.outputs.image}}
      - name: Terraform destroy
        if: github.ref == 'refs/heads/destroy'
        id: destroy
        working-directory: infracode/app
        run:  |
          terraform destroy -auto-approve -input=false -var-file=dev/terraform.tfvars -var "app_image=$APP_IMAGE"
        env:
          APP_IMAGE: ${{steps.build-image.outputs.image}}

